---
# - name: Install aptitude package
#   become: true
#   apt:
#     name: aptitude
#     state: present

- name: "upgrade packages."
  become: True
  shell: |
    apt -y update
    apt -y upgrade 

    
    

- name: "install dependencies."
  become: true
   shell: |
    apt install curl
    curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    apt install nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "install docker."
#   become: true
#   apt:
#     name: ["docker.io"]
#     state: latest
#     update_cache: yes


# - name: sudo usermod -aG docker root
#   become: True
#   shell:
#     cmd: "usermod -aG docker ubuntu"
#     chdir: .




# - name: Install docker-compose
#   remote_user: ubuntu
#   get_url: 
#     url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: 'u+x,g+x,o+x'

