---

- name: "upgrade packages."
  become: True
  shell: |
    apt -y update
    apt -y upgrade 



- name: "install docker."
  become: true
  apt:
    name: ["docker.io"]
    state: latest
    update_cache: yes


- name: sudo usermod -aG docker root
  become: True
  shell:
    cmd: "usermod -aG docker ubuntu"
    chdir: .




- name: Install docker-compose
  remote_user: ubuntu
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'


- copy:
    src: roles/deploy/files/docker-compose.yml
    dest: /home/ubuntu/prom



- name: Pull image
  shell: |
    cd /home/ubuntu/prom
    ls



# - name: Pull image
#   shell: |
#     cd /home/ubuntu/prom
#     docker-compose pull

# - name: Start prom
#   shell: |
#     cd /home/ubuntu/prom
#     docker-compose up -d
  