
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu

- copy:
    src: roles/deploy/artifactback.tar.gz
    dest: /home/ubuntu

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract artifactback.tar.gz to EC2
  unarchive:
    src: artifactback.tar.gz
    dest: /home/ubuntu

- copy:
    src: roles/deploy/files/run/docker-compose.yml
    dest: /home/ubuntu

- copy:
    src: roles/deploy/files/build/docker-compose.yml
    dest: /home/ubuntu/backend


- name: build image
  shell: |
    cd /home/ubuntu/backend
    docker-compose build -t sw-backend:latest backend
  args: 
    chdir: ./ 


- name: Start application
  shell: |
    docker-compose up -d
  args:
    chdir: ./



- name: Install NGINX
  become: True
  shell: |
    apt -y install nginx
    rm -rf /etc/nginx/sites-available/default

- copy:
    src: roles/deploy/tasks/default
    dest: /etc/nginx/sites-available/default


- name: check NGINX
  become: True
  shell: |
    nginx -t
    service nginx restart