
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu


- copy:
    src: roles/deploy/files/docker-compose.yml
    dest: /home/ubuntu


- name: Run command
  shell: |
    echo "Hello, world!"


- name: Pull image
  shell: |
    ls
    docker-compose pull
  
  args:
    chdir: ./


- name: Start application
  shell: |
    docker-compose up -d
  args:
    chdir: ./



- name: Install NGINX
  become: True
  shell: |
    apt -y install nginx
    rm -rf /etc/nginx/sites-available/default

- copy:
    src: roles/deploy/tasks/default
    dest: /etc/nginx/sites-available/default


- name: check NGINX
  become: True
  shell: |
    nginx -t
    service nginx restart