
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu


- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: "Start application"
  shell: |
    ls
    cd backend 
    pm2 stop default
    pm2 start -f server.js

- name: Install NGINX
  become: True
  shell: |
    apt -y install nginx
    rm -rf /etc/nginx/sites-available/default

- copy:
    src: roles/deploy/tasks/default
    dest: /etc/nginx/sites-available/default


- name: check NGINX
  become: True
  shell: |
    nginx -t
    service nginx restart