
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu


- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: "Start application"
  shell: |
    ls
    cd backend 
    pm2 stop default
    pm2 start -f server.js

- name: Install NGINX
  become: True
  apt:
    name: nginx
    state: present

- name: Create NGINX configuration file
  become: True
  template:
    src: node-app.conf.j2
    dest: /etc/nginx/sites-available/node-app.conf

- name: Enable NGINX configuration
  become: True
  file:
    src: /etc/nginx/sites-available/node-app.conf
    dest: /etc/nginx/sites-enabled/node-app.conf
    state: link

- name: Restart NGINX
  become: True
  service:
    name: nginx
    state: restarted
