
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Pull Image"
  shell: |
    docker pull yosefadel/sw-project-backend

- name: "Start application"
  shell: |
    ls
    cd server 
    docker run -p 3000:3000 -d -v $(pwd)/.env:/app/.env yosefadel/sw-project-backend

- name: Install NGINX
  become: True
  shell: |
    apt -y install nginx
    rm -rf /etc/nginx/sites-available/default

- copy:
    src: roles/deploy/tasks/default
    dest: /etc/nginx/sites-available/default


- name: check NGINX
  become: True
  shell: |
    nginx -t
    service nginx restart