
- copy:
    src: roles/deploy/artifact.tar.gz
    dest: /home/ubuntu


- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu


- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: "Start application"
  shell: |
    ls
    cd backend 
    pm2 stop default
    pm2 start -f server.js

- name: Install NGINX
  become: True
  apt:
    name: nginx
    state: present

- name: "Config nginx"
  become: True
  shell: |
    unlink /etc/nginx/sites-enabled/default
    tee /etc/nginx/conf.d/jenkins.conf <<EOF
      upstream jenkins {
          server 127.0.0.1:3000;
      }

      server {
          listen 80 default_server;
          listen [::]:80  default_server;
          location / {
              proxy_pass http://api;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
          }
      }
      EOF
    systemctl reload nginx
    